# Feeling Animals, by UgUnaii
# English is not my first language, so you will encounter gramaticall errors. Please don't mind.

# This is the plugin config. You can change it as you like, that's what it is for.

Config:
  # Enable this part to enable the plugin.
  enabled: true

  # The radius is the distance in blocks that will affect other animals and make them also flee.
  # Animals that are not in this zone will not be affected.
  distance-radius: 10

  # The list of animals that will make the the others when punched.
  animal-list:
    - COW
    - CHICKEN
    - PIG
    - SHEEP
    - HORSE

Messages:
  # This is the prefix that will appear in the beggining of some messages of the plugin.
  # Make sure there is a space at the end, if not, the messages will appear next to the prefix without a space.
  # If you want to remove the prefix, you can just let the prefix in blank, just like this "".
  prefix: "&8[&6Feeling Animals&8] "

  # From here on, you will see the different messages that the plugin will send.
  # You can change or translate them as you want.
  # The default color for every message is white (&f), so if you don't put a color indicator in the beggining of a message, it will be white.
  no-permission: "&cSorry&f, but you don't have the &cpermission &fto execute this command."

  config-reloaded: "The config has been &areloaded&f."

  argument-needed: "&cSorry&f, you must provide an &cargument&f."

  invalid-argument: "&cSorry&f, the argument that you provided is &cinvalid&f."

  # You can use the variable ${version} where you like the most, but only in this message, in the others will not work.
  display-version: "The current version from the plugin is: ${version}"

  get-help: "If you need help, try using the &6/fa help &fcommand."

  # Here you can use the char \n to make a line jump.
  display-help: "This are the commands and their usage that the plugin provides.\n
  The main command is &6/feelinganimals &for &6/fa &ffor abbreviation.\n
  - &6/fa help &fdisplays this message.\n
  - &6/fa version &fdisplays the version of the plugin.\n
  - &6/fa reload &freloads the config file of the plugin."
